// <auto-generated />
using System;
using Acceloka.Api.Infrastructure.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accelist_Acceloka_Ticketing_Api_Service.Migrations
{
    [DbContext(typeof(AccelokaDbContext))]
    partial class AccelokaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acceloka.Api.Domain.BookedTicket", b =>
                {
                    b.Property<string>("BookedTicketId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BookedTicketId");

                    b.Property<string>("KodeTiket")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KodeTiket");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BookingDate");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("Qty");

                    b.HasKey("BookedTicketId", "KodeTiket");

                    b.HasIndex("KodeTiket");

                    b.ToTable("Bookedtiket", (string)null);
                });

            modelBuilder.Entity("Acceloka.Api.Domain.Ticket", b =>
                {
                    b.Property<string>("KodeTiket")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KodeTiket");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EventDate");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Harga");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kategori");

                    b.Property<string>("NamaTiket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamaTiket");

                    b.Property<int>("Quota")
                        .HasColumnType("int")
                        .HasColumnName("Quota");

                    b.HasKey("KodeTiket");

                    b.ToTable("tiket", (string)null);
                });

            modelBuilder.Entity("Acceloka.Api.Domain.BookedTicket", b =>
                {
                    b.HasOne("Acceloka.Api.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("KodeTiket")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
